# Generated by Django 4.2.30 on 2026-08-16 23:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Document File')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Extracted Content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retrieval_latency_ms', models.IntegerField(blank=True, help_text='Total retrieval latency in milliseconds', null=True)),
                ('selected_chunk_ids', models.JSONField(blank=True, help_text='List of chunk ids used for the final context', null=True)),
                ('chunk_score_map', models.JSONField(blank=True, help_text='Map of chunk_id -> {score, rerank_score, source_doc, position}', null=True)),
                ('llm_model', models.CharField(blank=True, help_text='Model name that processed the request (primary or fallback)', max_length=256, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('insufficient_info', 'Insufficient Information')], default='success', max_length=32)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_qahist_created_926b39_idx'), models.Index(fields=['status'], name='core_qahist_status_1cd75d_idx')],
            },
        ),
    ]
