# Generated by Django 4.2.30 on 2026-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مرحله فعلی'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'In the Waiting list'), ('processing', 'Processing (please wait)'), ('completed', 'Processing completed successfully.'), ('failed', 'Processing error')], default='pending', max_length=50, verbose_name='وضعیت نهایی'),
        ),
    ]
